version: '3.8'

services:
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  redis_init:
    image: redis:6-alpine
    command: redis-cli -h redis CONFIG SET notify-keyspace-events Ex
    depends_on:
      - redis

  db:
    image: postgres:14.0
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - ./.env

  nginx:
    image: nginx:1.20
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html/:/usr/share/nginx/html/
    depends_on:
      - web

#  worker:
#    build: ../service
#    command: celery -A notifications.worker worker --loglevel=info --logfile=notifications/logs/celery.log
#    volumes:
#      - ../service:/service
#    depends_on:
#      - web
#      - redis

#  dashboard:
#    build: ../service
#    command: celery -A notifications.worker flower --port=5555 --broker=redis://redis:6379/0
#    ports:
#      - "5556:5555"
#    depends_on:
#      - worker
